# Generated by Django 3.0.4 on 2020-03-31 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='author',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='publish',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publish',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
