# Generated by Django 3.0.4 on 2020-04-01 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publish', '0002_auto_20200331_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='publish',
            name='publish_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='publish',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
