# Generated by Django 3.0.4 on 2020-04-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_publish_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='tech',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publish',
            name='github',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
