# Generated by Django 3.0.4 on 2020-04-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
