# Generated by Django 3.0.4 on 2020-04-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_auto_20200403_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/image'),
        ),
    ]
