# Generated by Django 3.0.4 on 2020-04-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_auto_20200403_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='tech',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
